config/routes.rb
Rails.application.routes.draw do

  resources :sections
  devise_for :admins
  resources :phone_numbers
  mount Koudoku::Engine, at: 'koudoku'
  scope module: 'koudoku' do
    get 'pricing' => 'subscriptions#index', as: 'pricing'
  end

  resources :tutorials
  resources :services
  resources :activities
  resources :settings
  resources :reminders
  resources :recurring_shifts
  resources :shifts
  resources :clients
  resources :contacts
  resources :offices do
    collection do
      get :show_telephone
    end
  end

  resources :caregivers
  resources :calls
  resources :dashboard
  resources :reports
  resources :landing
  resources :schedule
  resources :digital_signature

  get "caregivers/show"
  post 'calls/voice' => 'calls#voice'
  match 'calls/get_employee' => 'calls#get_employee', via: [:get, :post], as: 'get_employee'
  match 'calls/verify_caller' => 'calls#verify_caller', via: [:get, :post], as: 'verify_caller'
  match 'calls/play_voice' => 'calls#play_voice', via: [:get, :post], as: 'play_voice'
  match 'calls/clock_out' => 'calls#clock_out', via: [:get, :post], as: 'clock_out'
  match 'calls/clock_in' => 'calls#clock_in', via: [:get, :post], as: 'clock_in'
  match 'calls/ask' => 'calls#ask', via: [:get, :post], as: 'ask'
  match 'calls/answer' => 'calls#answer', via: [:get, :post], as: 'answer'
  match 'calls/ask_for_employee_code' => 'calls#ask_for_employee_code', via: [:get, :post], as: 'ask_for_employee_code'
  get 'display_client' => "clients#display_client"
  get 'call_logs' => "reports#call_logs", as: 'call_logs'
  post 'call_logs' => "reports#call_logs", as: 'search_call_logs'
  get 'timecard_report' => "reports#timecard_report", as: 'timecard_report'
  post 'timecard_report' => "reports#timecard_report", as: 'search_timecard_report'
  get 'activity_report' => "reports#activity_report", as: 'activity_report'
  post 'activity_report' => "reports#activity_report", as: 'search_activity_report'
  get 'custom_prompt_report' => "reports#custom_prompt_report", as: 'custom_prompt_report'
  post 'custom_prompt_report' => "reports#custom_prompt_report", as: 'search_custom_prompt_report'
  get 'evv_recording' => "reports#evv_recording", as: 'evv_recording'
  post 'evv_recording' => "reports#evv_recording", as: 'search_evv_recording'
  get 'quickstart' => "tutorials#quickstart", as: 'quickstart'
  get 'quickstart_step2' => "tutorials#quickstart_step2", as: 'quickstart_step2'
  get 'quickstart_step3' => "tutorials#quickstart_step3", as: 'quickstart_step3'
  get 'terms_and_conditions' => "tutorials#terms_and_conditions", as: 'terms_and_conditions'
  match 'digital_signature/confirm' => 'digital_signature#confirm', via: [:get, :post], as: 'confirm'
  match 'digital_signature/select_client' => 'digital_signature#select_client', via: [:get, :post], as: 'select_client'
  match 'display_question' => 'digital_signature#display_question', via: [:get, :post], as: 'display_question'
  get 'employee_code' => "digital_signature#employee_code", as: 'employee_code'
  get 'verify' => "digital_signature#verify", as: 'verify'
  get 'timesheet' => "digital_signature#timesheet", as: 'timesheet'
  get 'verify_location' => "digital_signature#verify_location", as: 'verify_location'
  put 'update_timesheet', to: 'digital_signature#update_timesheet', as: "update_timesheet"
  get 'congrats' => "digital_signature#congrats", as: 'congrats'

  get 'obtain_prospect' => "settings#obtain_prospect", as: 'obtain_prospect'
  get 'export', to: 'settings#export', as: :foo_export
  get 'call_process' => "dashboard#call_process", as: 'call_process'
  get 'digital_timesheet_process' => "dashboard#digital_timesheet_process", as: 'digital_timesheet_process'
  get 'weekly_report' => "reports#weekly_report", as: 'weekly_report'
  post 'weekly_report' => "reports#weekly_report", as: 'post_weekly_report'
  get 'search_weekly_report' => "reports#search_weekly_report", as: 'search_weekly_report'

  match 'tutorials/demo_explained' => 'tutorials#demo_explained', via: [:get, :post], as: 'demo_explained'
  post 'demo' => "tutorials#demo", as: 'post_demo'
  get 'demo' => "tutorials#demo", as: 'demo'
  
  get 'start_guide' => "tutorials#start_guide", as: 'start_guide'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get "/signup"   => "devise/registrations#new"
    get 'login', to: 'devise/sessions#new'
    get 'agency_details', to: 'devise/registrations#edit'
    put 'update_agency', to: 'users/registrations#update', as: "update_agency"

  end

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  root 'dashboard#index'

end

app/models/office.rb
class Office < ActiveRecord::Base

  validates_presence_of :name
  # validates_presence_of :office_code # on me


  belongs_to :user
  has_one :location
  has_one :contact
  has_many :activities
  has_many :clients
  has_many :caregivers
  has_many :shifts
  has_one :supervisor, class_name: "Caregiver"

  # belongs_to :author, class_name: "User"

  def set_code(user)
    unless self.office_code and self.office_code.length > 2
      # get all codes
      all_codes = []
      user.offices.each do |o|
        all_codes.push o.office_code
      end
      done = false
      while done == false
        code = 3.times.map { rand(1..9) }.join.to_i
        if all_codes.include? code
          done = false
        else
          done = true
        end
      end
      self.office_code = code
      self.save
      return office_code
    end
  end

# user created office
  def save_activity(text, office, user)
    activity = Activity.new(activity:text)
    activity.office = office
    activity.user = user
    activity.save
  end

  # user set office supervisor
    def set_supervisor_activity(text, office, user, employee)
      activity = Activity.new(activity:text)
      activity.caregiver = employee
      activity.office = office
      activity.user = user
      activity.save
    end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = current_user.offices

    if current_user.caregivers.count == 0
      redirect_to "/caregivers/new"
    elsif current_user.clients.count == 0
      redirect_to "/clients/new"
    end
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
    @activities = set_activities
    @activities.sort_by(&:created_at).reverse
    count_calls # get the amount of calls
    create_contact
  end

  def set_activities
    @activities = []
    @office.activities.each do |a|
      @activities.push a
      @activities.sort_by(&:created_at).reverse
    end
    @office.clients.each do |c|
      c.activities.each do |a|
        @activities.push a
      end
      @activities.sort_by(&:created_at).reverse
    end
    @office.caregivers.each do |c|
      c.activities.each do |a|
        @activities.push a
      end
      @activities.sort_by(&:created_at).reverse
    end
    @office.shifts.each do |c|
      c.activities.each do |a|
        @activities.push a
      end
      @activities.sort_by(&:created_at).reverse
    end
    return @activities.sort_by(&:created_at).reverse

    # @activities = Activity.where("client = 'Rails 3' OR activity = 'Rails 4'")
  end


  def count_calls
    @calls = 0
    clients = @office.clients
    clients.each do |c|
      c.calls.each do |call|
        @calls += 1
      end
    end
  end

  def create_contact
    @contact = Contact.new
  end

  # def save_office_contact
  #   if @office.contact.email or @office.contact.home_number or @office.contact.mobile_number
  #     # Save contant as office.contact
  #     @office.contact.save
  #   end
  # end


  # GET /offices/new
  def new
    @office = Office.new
    set_caregivers

  end

  # GET /offices/1/edit
  def edit
    set_caregivers
  end

  def set_caregivers
    caregivers = []
    current_user.offices.each do |o|
      o.caregivers.each do |c|
        caregivers.push c
      end
    end
    @caregivers = caregivers
  end
  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        save_office
        # save_office_contact
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        set_supervisor
        # save_office_contact
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    clear_all_connections
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def clear_all_connections
    @office.shifts.clear
    @office.caregivers.clear
    @office.activities.clear
    @office.clients.clear
    @office.supervisor = nil
    @office.save
  end


  def save_office
    @office.set_code(current_user)
    unless current_user.offices.include? @office
      current_user.offices.push @office
    end
    #record activity
    @office.save_activity("#{current_user.name} created an office: #{@office.name}.", @office, current_user)
    set_supervisor
  end

  def set_supervisor
    if params[:supervisor_id]
      # find superviser
      sv = Caregiver.find_by_id(params[:supervisor_id])
      if sv
        @office.set_supervisor_activity("#{current_user.name} set #{sv.name} as supervisor for #{@office.name}",
          @office, current_user, @office.supervisor)
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:name, :telephone, :office_code, :email, :supervisor_id,
       :location, :state, :city, :postcode, :address)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper


end

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
  <div class="m-t" role="form" >
    <% if @office.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

        <ul>
        <% @office.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>Create Office </h5>
          <div class="ibox-tools">
              <a class="collapse-link">
                  <i class="fa fa-chevron-up"></i>
              </a>
              <a class="close-link">
                  <i class="fa fa-times"></i>
              </a>
          </div>
      </div>
      <div class="ibox-content">
          <div class="field">
            <div class="form-group"><label class="col-sm-2 control-label">Name</label>
              <div class="row">
                <div class="col-sm-6">
                  <%= f.text_field :name, class:"form-control" %>
                  <span class="help-block m-b-none">Enter the Name of the Office. May even be the name of your Agency</span>
                  <br>
                </div>
              </div>
            </div>
          </div>




          <div class="form-group">
            <label class="col-sm-2 control-label">Phone</label>
              <div class="row">
                <div class="col-sm-4">
                    <%= f.text_field :telephone, class:"form-control", :data => {:mask=> '(999) 999-9999'} %>
                    <span class="help-block">(123) 456-7890   (Optional)</span>
                    <br>
                </div>
              </div>
          </div>

          <%if current_user.caregivers.count > 0%>

            <div class="field">
              <div class="form-group"><label class="col-sm-2 control-label">Select Supervisor</label>
                <div class="row">
                  <div class="col-sm-4">
                    <%= f.collection_select :supervisor_id, current_user.caregivers, :id, :name,
                      {:class => 'prevent_collapse'},:class => "form-control m-b", :include_blank => 'Select' %>
                  </div>
                </div>
              </div>
            </div>

          <%end%>



                    <div class="field row">
                      <div class="col-sm-12">
                        <div class="form-group"><label class="col-sm-2 control-label">Address</label>
                        <div class="col-sm-7">
                          <%= f.text_field :address, class:"form-control" %>
                          <br>
                          <br>
                        </div>
                        </div>
                      </div>

                    </div>


                    <div class="field row">
                      <div class="col-sm-12">
                        <div class="form-group"><label class="col-sm-2 control-label">City</label>
                        <div class="col-sm-6">
                          <%= f.text_field :city, class:"form-control" %>
                          <br>
                        </div>
                        </div>
                      </div>
                    </div>

                    <div class="field row">
                      <div class="col-sm-12">
                      <div class="form-group"><label class="col-md-2 control-label">State</label>
                        <div class="col-md-4">
                            <%= f.collection_select :state, ["Alaska",
                                      "Alabama",
                                      "Arkansas",
                                      "American Samoa",
                                      "Arizona",
                                      "California",
                                      "Colorado",
                                      "Connecticut",
                                      "District of Columbia",
                                      "Delaware",
                                      "Florida",
                                      "Georgia",
                                      "Guam",
                                      "Hawaii",
                                      "Iowa",
                                      "Idaho",
                                      "Illinois",
                                      "Indiana",
                                      "Kansas",
                                      "Kentucky",
                                      "Louisiana",
                                      "Massachusetts",
                                      "Maryland",
                                      "Maine",
                                      "Michigan",
                                      "Minnesota",
                                      "Missouri",
                                      "Mississippi",
                                      "Montana",
                                      "North Carolina",
                                      " North Dakota",
                                      "Nebraska",
                                      "New Hampshire",
                                      "New Jersey",
                                      "New Mexico",
                                      "Nevada",
                                      "New York",
                                      "Ohio",
                                      "Oklahoma",
                                      "Oregon",
                                      "Pennsylvania",
                                      "Puerto Rico",
                                      "Rhode Island",
                                      "South Carolina",
                                      "South Dakota",
                                      "Tennessee",
                                      "Texas",
                                      "Utah",
                                      "Virginia",
                                      "Virgin Islands",
                                      "Vermont",
                                      "Washington",
                                      "Wisconsin",
                                      "West Virginia",
                                      "Wyoming"], :to_s, :to_s,
                                      {:class => 'prevent_collapse'},:class => "form-control m-b" %>
                                      <br><br><br><br>
                          </div>
                        </div>
                      </div>
                    </div>




          <div class="actions">
              <%= f.submit nil, class: "btn btn-primary block full-width m-b" %>
          </div>

          <div class="actions">
            <%if @office.id%>
                <%= link_to "Delete Office", office_path(@office), :method => :delete,  data: {confirm: 'Are you sure?' },
                  :class => "btn btn-danger block half-width m-b btn-outline" %>
            <%end%>
          </div>
      </div>
    </div>

  </div>

<% end %>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form' %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-10">
        <h2>Offices</h2>
        <ol class="breadcrumb">
            <li>
                <a href="/">Dashboard</a>
            </li>
            <li class="active">
                <strong>Offices</strong>
            </li>
        </ol>
        <a href="/offices/new" class="btn btn-w-m btn-success">Create Office</a>


    </div>
    <div class="col-sm-2">

    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
      <%current_user.offices.each do |o|%>
        <div class="row-lg-4">
            <div class="ibox">
                <div class="ibox-title">
                    <span class="label label-primary pull-right">ACTIVE</span>
                    <h5> <%= o.name%> </h5>
                </div>
                <div class="ibox-content">
                    <%if o.address%>
                      <h4><%= o.address%></h4>
                    <% else %>
                    <h4>No Address</h4>
                    <% end %>
                    <p>
                      <%if o.shifts.count > 0%>
                        <% if o.shifts.order('updated_at DESC').first.start_time > Time.now and o.shifts.order('updated_at DESC').first.end_time < Time.now %>
                          Lastest Shift: <%= o.shifts.order('updated_at DESC').first.caregiver.name %> is currently assisting <%= o.shifts.order('updated_at DESC').first.client.name %>
                        <%elsif  Time.now and o.shifts.order('updated_at DESC').first.end_time > Time.now%>
                          Lastest Shift: <%= o.shifts.order('updated_at DESC').first.caregiver.name %> finished assisting <%= o.shifts.order('updated_at DESC').first.client.name %>
                        <%else%>
                          Upcoming Shift: <%= o.shifts.order('updated_at DESC').first.caregiver.name %> will assist <%= o.shifts.order('updated_at DESC').first.client.name %>
                        <%end%>
                      <%else%>
                        No News
                      <%end%>
                    </p>

                    <div class="row  m-t-sm">
                        <div class="col-sm-4">
                            <div class="font-bold">CLIENTS</div>
                            <%= o.clients.count%>
                        </div>
                        <div class="col-sm-4">
                            <div class="font-bold">EMPLOYEES</div>
                            <%= o.caregivers.count%>
                        </div>
                        <a href="/offices/<%=o.id%>" class="btn btn-w-m btn-success pull-right">View Office</a>

                    </div>

                </div>
            </div>
        </div>
      <% end %>
    </div>

<br>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form' %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-10">
        <h2><%=@office.name%></h2>
        <ol class="breadcrumb">
            <li>
                <a href="/">Dashboard</a>
        </li>
        <li>
            <a href="/offices">Offices</a>
        </li>
        <li class="active">
            <strong><%=@office.name%></strong>
        </li>
    </ol>
</div>
<div class="col-sm-2">

</div>
        </div>
<div class="wrapper wrapper-content">
<div class="row animated fadeInRight">
    <div class="col-md-4">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Details</h5>
            </div>
            <div>
                <div class="ibox-content no-padding border-left-right">
                    <img alt="image" class="img-responsive" src="<%= image_path('office_building.jpg') %>">
                </div>
                <div class="ibox-content profile-content">
                    <h4><strong><%=@office.name%></strong></h4>
                    <%if @office.location and @office.location.address%>
                      <p><i class="fa fa-map-marker"></i> <%= @office.location.address%></p>
                    <%end%>
                    <h5>
                        About
                    </h5>
                    <p>
                      <%if @office.supervisor and @office.supervisor.name %>
                        Lead by <%=@office.supervisor.name%>, this office has managed over <%=@office.shifts.where('created_at > ?', 7.days.ago).count%> shifts in the last week. It now has <%=@office.caregivers.count%> employees and <%=@office.clients.count%> clients.
                      <%end%>
                    </p>
                    <p>
                      <%if @office.office_code %>
                        <strong>Office Code: </strong> <%= @office.office_code %>
                      <%else%>
                        <%=@office.set_code(current_user)%>
                      <%end%>
                    </p>
                    <div class="row m-t-lg">
                        <div class="col-md-4">
                            <span class="bar">5,3,9,6,5,9,7,3,5,2</span>
                            <h5><strong><%=@calls%></strong> Calls</h5>
                        </div>
                        <div class="col-md-4">
                            <span class="line">5,3,9,6,5,9,7,3,5,2</span>
                            <h5><strong><%=@office.shifts.count%></strong> Shifts</h5>
                        </div>
                        <div class="col-md-4">
                            <span class="bar">5,3,2,-1,-3,-2,2,3,5,2</span>
                            <h5><strong><%=@office.clients.count%></strong> Clients</h5>
                        </div>
                    </div>
                    <div class="user-button">
                        <div class="row">
                            <div class="col-md-6">
                              <%if @office.telephone%>
                                <%= link_to "#" do %>
                                  <button type="button" class="btn btn-primary btn-sm btn-block" onclick ='alert("Phone Number: <%=@office.telephone%>")'><i class="fa fa-envelope"></i>  Contact</button>
                                <%end%>
                              <%end%>
                            </div>
                            <div class="col-md-6">
                              <%= link_to edit_office_path do %>
                                <button type="button" class="btn btn-default btn-sm btn-block"><i class="fa fa-gear"></i>  Edit</button>
                              <%end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Activites</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#">Config option 1</a>
                        </li>
                        <li>
                            <a href="#">Config option 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">

                <div>
                    <div class="feed-activity-list">
                      <%@activities.each do |a|%>
                        <div class="feed-element">
                            <a href="#" class="pull-left">
                                <i class="fa fa-plus-square"></i>
                                <!-- <img alt="image" class="img-circle" src="<%= image_path('a1.jpg') %>"> -->
                            </a>
                            <div class="media-body ">
                                <small class="pull-right text-navy"><%=local_time_ago(a.created_at)%></small>
                                 <%=a.activity%> <br>
                              <%if a.created_at.today?%>
                                <!-- <small class="text-muted">Today <%=DateTime.parse("#{a.created_at}").strftime("%l:%M %p - %m.%d.%Y")%> - 12.06.2014</small> -->
                              <%else%>
                                <!-- <small class="text-muted"><%=local_time_ago(a.created_at)%>.strftime("%l:%M %p")%></small> -->
                              <%end%>

                            </div>
                        </div>
                      <%end%>

                    </div>

                    <!-- <button class="btn btn-primary btn-block m"><i class="fa fa-arrow-down"></i> Show More</button> -->

                </div>

            </div>
        </div>

    </div>
</div>
</div>


<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $("span.pie").peity("pie", {
        fill: ['#1ab394', '#d7d7d7', '#ffffff']
    })

    $(".line").peity("line", {
        fill: '#1ab394',
        stroke: '#169c81',
    })

    $(".bar").peity("bar", {
        fill: ["#1ab394", "#d7d7d7"]
    })


});

</script>

<% end %>