config/routes.rb
Rails.application.routes.draw do

  resources :sections
  devise_for :admins
  resources :phone_numbers
  mount Koudoku::Engine, at: 'koudoku'
  scope module: 'koudoku' do
    get 'pricing' => 'subscriptions#index', as: 'pricing'
  end

  resources :tutorials
  resources :services
  resources :activities
  resources :settings
  resources :reminders
  resources :recurring_shifts
  resources :shifts
  resources :clients
  resources :contacts
  resources :offices do
    collection do
      get :show_telephone
    end
  end

  resources :caregivers
  resources :calls
  resources :dashboard
  resources :reports
  resources :landing
  resources :schedule
  resources :digital_signature

  get "caregivers/show"
  post 'calls/voice' => 'calls#voice'
  match 'calls/get_employee' => 'calls#get_employee', via: [:get, :post], as: 'get_employee'
  match 'calls/verify_caller' => 'calls#verify_caller', via: [:get, :post], as: 'verify_caller'
  match 'calls/play_voice' => 'calls#play_voice', via: [:get, :post], as: 'play_voice'
  match 'calls/clock_out' => 'calls#clock_out', via: [:get, :post], as: 'clock_out'
  match 'calls/clock_in' => 'calls#clock_in', via: [:get, :post], as: 'clock_in'
  match 'calls/ask' => 'calls#ask', via: [:get, :post], as: 'ask'
  match 'calls/answer' => 'calls#answer', via: [:get, :post], as: 'answer'
  match 'calls/ask_for_employee_code' => 'calls#ask_for_employee_code', via: [:get, :post], as: 'ask_for_employee_code'
  get 'display_client' => "clients#display_client"
  get 'call_logs' => "reports#call_logs", as: 'call_logs'
  post 'call_logs' => "reports#call_logs", as: 'search_call_logs'
  get 'timecard_report' => "reports#timecard_report", as: 'timecard_report'
  post 'timecard_report' => "reports#timecard_report", as: 'search_timecard_report'
  get 'activity_report' => "reports#activity_report", as: 'activity_report'
  post 'activity_report' => "reports#activity_report", as: 'search_activity_report'
  get 'custom_prompt_report' => "reports#custom_prompt_report", as: 'custom_prompt_report'
  post 'custom_prompt_report' => "reports#custom_prompt_report", as: 'search_custom_prompt_report'
  get 'evv_recording' => "reports#evv_recording", as: 'evv_recording'
  post 'evv_recording' => "reports#evv_recording", as: 'search_evv_recording'
  get 'quickstart' => "tutorials#quickstart", as: 'quickstart'
  get 'quickstart_step2' => "tutorials#quickstart_step2", as: 'quickstart_step2'
  get 'quickstart_step3' => "tutorials#quickstart_step3", as: 'quickstart_step3'
  get 'terms_and_conditions' => "tutorials#terms_and_conditions", as: 'terms_and_conditions'
  match 'digital_signature/confirm' => 'digital_signature#confirm', via: [:get, :post], as: 'confirm'
  match 'digital_signature/select_client' => 'digital_signature#select_client', via: [:get, :post], as: 'select_client'
  match 'display_question' => 'digital_signature#display_question', via: [:get, :post], as: 'display_question'
  get 'employee_code' => "digital_signature#employee_code", as: 'employee_code'
  get 'verify' => "digital_signature#verify", as: 'verify'
  get 'timesheet' => "digital_signature#timesheet", as: 'timesheet'
  get 'verify_location' => "digital_signature#verify_location", as: 'verify_location'
  put 'update_timesheet', to: 'digital_signature#update_timesheet', as: "update_timesheet"
  get 'congrats' => "digital_signature#congrats", as: 'congrats'

  get 'obtain_prospect' => "settings#obtain_prospect", as: 'obtain_prospect'
  get 'export', to: 'settings#export', as: :foo_export
  get 'call_process' => "dashboard#call_process", as: 'call_process'
  get 'digital_timesheet_process' => "dashboard#digital_timesheet_process", as: 'digital_timesheet_process'
  get 'weekly_report' => "reports#weekly_report", as: 'weekly_report'
  post 'weekly_report' => "reports#weekly_report", as: 'post_weekly_report'
  get 'search_weekly_report' => "reports#search_weekly_report", as: 'search_weekly_report'

  match 'tutorials/demo_explained' => 'tutorials#demo_explained', via: [:get, :post], as: 'demo_explained'
  post 'demo' => "tutorials#demo", as: 'post_demo'
  get 'demo' => "tutorials#demo", as: 'demo'
  
  get 'start_guide' => "tutorials#start_guide", as: 'start_guide'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get "/signup"   => "devise/registrations#new"
    get 'login', to: 'devise/sessions#new'
    get 'agency_details', to: 'devise/registrations#edit'
    put 'update_agency', to: 'users/registrations#update', as: "update_agency"

  end

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  root 'dashboard#index'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/settings_controller.rb
require "csv"
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end


  def obtain_prospect
    url = "https://npidb.org/organizations/agencies/in-home-supportive-care_253z00000x/1497012322.aspx"
    uri = params[:uri]
    @html = search_homecare_prospect(uri)#"kl"

    @urls = ["https://npidb.org/organizations/agencies/home-health_251e00000x/1619270691.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1740597954.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1578956298.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1710016258.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1013292200.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1336414325.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1659569457.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1063552198.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1962596957.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1720347628.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1477831162.aspx",
      "https://npidb.org/organizations/agencies/home-health_251e00000x/1326323908.aspx",
       "https://npidb.org/organizations/agencies/in-home-supportive-care_253z00000x/1265842421.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1790803807.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1790862407.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1235436940.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1699879601.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1073874087.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1154571479.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1609312305.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1891864310.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1225149743.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1912130881.aspx",
        "https://npidb.org/organizations/agencies/home-health_251e00000x/1992193833.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1215233911.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1023557071.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1932432226.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1326580424.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1114284643.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1073913539.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1538429147.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1346658267.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1699195206.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1225135122.aspx",
        "https://npidb.org/organizations/agencies/home-health_251e00000x/1649729484.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1689679672.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1245388420.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1205038999.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1144552605.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1669712329.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1881839306.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1659604569.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1598171811.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1558658096.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1851600605.aspx",
        "https://npidb.org/organizations/agencies/home-health_251e00000x/1477899342.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1154603942.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1821395872.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1972807634.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1093996472.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1457766024.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1679782494.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1871864058.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1548522576.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1932447315.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1477829828.aspx",
        "https://npidb.org/organizations/agencies/home-health_251e00000x/1992997365.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1770895948.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1306091160.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1720415755.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1871920728.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1730367715.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1902885312.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1902178130.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1225130669.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1124041892.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1619068418.aspx",
        "https://npidb.org/organizations/agencies/home-health_251e00000x/1992095632.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1639315278.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1750336434.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1861786287.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1922393297.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1427398049.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1285061523.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1588107965.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1114350196.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1396974929.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1083984769.aspx",
        "https://npidb.org/organizations/agencies/home-health_251e00000x/1265869770.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1184863995.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1891022042.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1043631781.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1457672065.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1477708899.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1144651795.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1902197999.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1720332521.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1932418530.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1144551201.aspx",
         "https://npidb.org/organizations/agencies/home-health_251e00000x/1497823785.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1912213463.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1407095441.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1487977823.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1205376084.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1013292200.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1770844870.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1659463115.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1710395272.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1326273012.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1942637673.aspx",
          "https://npidb.org/organizations/agencies/home-health_251e00000x/1710907704.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1881770899.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1851620223.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1043417512.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1134382682.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1275811697.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1730483389.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1265972343.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1447510086.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1881951481.aspx", "https://npidb.org/organizations/agencies/home-health_251e00000x/1992863617.aspx",

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :allow_reminder_for_birthdays %><br>
    <%= f.check_box :allow_reminder_for_birthdays %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-10">
        <h2>Settings</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'dashboard', :action => 'index' %>">Dashboard</a>
            </li>
            <li class="active">
                <strong>Settings</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-2">
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

  <div class="vote-item">
      <div class="row">
          <div class="col-md-10">
              <a href="/agency_details" class="vote-title">
                  Account Information
              </a>
          </div>
          <div class="col-md-2 ">
              <div class="vote-icon">
                  <i class="fa fa-id-card"> </i>
              </div>
          </div>
      </div>
  </div>
  <div class="vote-item">
      <div class="row">
          <div class="col-md-10">
            <%if current_user%>
              <a href="<%=koudoku.owner_subscriptions_path(current_user)%>" class="vote-title">
            <%else%>
              <a href="/pricing" class="vote-title">
            <%end%>
                  Subscription / Payment Method
              </a>
          </div>
          <div class="col-md-2 ">
              <div class="vote-icon">
                  <i class="fa fa-cc-visa"> </i>
              </div>
          </div>
      </div>
  </div>
  <div class="vote-item">
      <div class="row">
          <div class="col-md-10">
              <a href="/services" class="vote-title">
                  Call Configuration
              </a>
          </div>
          <div class="col-md-2 ">
              <div class="vote-icon">
                  <i class="fa fa-phone-square"> </i>
              </div>
          </div>
      </div>
  </div>
  <div class="vote-item">
      <div class="row">
          <div class="col-md-10">
              <a href="/tutorials" class="vote-title">
                  Tutorials
              </a>
          </div>
          <div class="col-md-2 ">
              <div class="vote-icon">
                  <i class="fa fa-graduation-cap"> </i>
              </div>
          </div>
      </div>
  </div>
</div>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/obtain_prospect.html.erb
<p><%=@data%></p>

<p><%=@html%></p>

<%= link_to "Export Data", foo_export_path(format: "csv") %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @setting.first_name %>
</p>

<p>
  <strong>Allow reminder for birthdays:</strong>
  <%= @setting.allow_reminder_for_birthdays %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>