config/routes.rb
Rails.application.routes.draw do

  resources :sections
  devise_for :admins
  resources :phone_numbers
  mount Koudoku::Engine, at: 'koudoku'
  scope module: 'koudoku' do
    get 'pricing' => 'subscriptions#index', as: 'pricing'
  end

  resources :tutorials
  resources :services
  resources :activities
  resources :settings
  resources :reminders
  resources :recurring_shifts
  resources :shifts
  resources :clients
  resources :contacts
  resources :offices do
    collection do
      get :show_telephone
    end
  end

  resources :caregivers
  resources :calls
  resources :dashboard
  resources :reports
  resources :landing
  resources :schedule
  resources :digital_signature

  get "caregivers/show"
  post 'calls/voice' => 'calls#voice'
  match 'calls/get_employee' => 'calls#get_employee', via: [:get, :post], as: 'get_employee'
  match 'calls/verify_caller' => 'calls#verify_caller', via: [:get, :post], as: 'verify_caller'
  match 'calls/play_voice' => 'calls#play_voice', via: [:get, :post], as: 'play_voice'
  match 'calls/clock_out' => 'calls#clock_out', via: [:get, :post], as: 'clock_out'
  match 'calls/clock_in' => 'calls#clock_in', via: [:get, :post], as: 'clock_in'
  match 'calls/ask' => 'calls#ask', via: [:get, :post], as: 'ask'
  match 'calls/answer' => 'calls#answer', via: [:get, :post], as: 'answer'
  match 'calls/ask_for_employee_code' => 'calls#ask_for_employee_code', via: [:get, :post], as: 'ask_for_employee_code'
  get 'display_client' => "clients#display_client"
  get 'call_logs' => "reports#call_logs", as: 'call_logs'
  post 'call_logs' => "reports#call_logs", as: 'search_call_logs'
  get 'timecard_report' => "reports#timecard_report", as: 'timecard_report'
  post 'timecard_report' => "reports#timecard_report", as: 'search_timecard_report'
  get 'activity_report' => "reports#activity_report", as: 'activity_report'
  post 'activity_report' => "reports#activity_report", as: 'search_activity_report'
  get 'custom_prompt_report' => "reports#custom_prompt_report", as: 'custom_prompt_report'
  post 'custom_prompt_report' => "reports#custom_prompt_report", as: 'search_custom_prompt_report'
  get 'evv_recording' => "reports#evv_recording", as: 'evv_recording'
  post 'evv_recording' => "reports#evv_recording", as: 'search_evv_recording'
  get 'quickstart' => "tutorials#quickstart", as: 'quickstart'
  get 'quickstart_step2' => "tutorials#quickstart_step2", as: 'quickstart_step2'
  get 'quickstart_step3' => "tutorials#quickstart_step3", as: 'quickstart_step3'
  get 'terms_and_conditions' => "tutorials#terms_and_conditions", as: 'terms_and_conditions'
  match 'digital_signature/confirm' => 'digital_signature#confirm', via: [:get, :post], as: 'confirm'
  match 'digital_signature/select_client' => 'digital_signature#select_client', via: [:get, :post], as: 'select_client'
  match 'display_question' => 'digital_signature#display_question', via: [:get, :post], as: 'display_question'
  get 'employee_code' => "digital_signature#employee_code", as: 'employee_code'
  get 'verify' => "digital_signature#verify", as: 'verify'
  get 'timesheet' => "digital_signature#timesheet", as: 'timesheet'
  get 'verify_location' => "digital_signature#verify_location", as: 'verify_location'
  put 'update_timesheet', to: 'digital_signature#update_timesheet', as: "update_timesheet"
  get 'congrats' => "digital_signature#congrats", as: 'congrats'

  get 'obtain_prospect' => "settings#obtain_prospect", as: 'obtain_prospect'
  get 'export', to: 'settings#export', as: :foo_export
  get 'call_process' => "dashboard#call_process", as: 'call_process'
  get 'digital_timesheet_process' => "dashboard#digital_timesheet_process", as: 'digital_timesheet_process'
  get 'weekly_report' => "reports#weekly_report", as: 'weekly_report'
  post 'weekly_report' => "reports#weekly_report", as: 'post_weekly_report'
  get 'search_weekly_report' => "reports#search_weekly_report", as: 'search_weekly_report'

  match 'tutorials/demo_explained' => 'tutorials#demo_explained', via: [:get, :post], as: 'demo_explained'
  post 'demo' => "tutorials#demo", as: 'post_demo'
  get 'demo' => "tutorials#demo", as: 'demo'
  
  get 'start_guide' => "tutorials#start_guide", as: 'start_guide'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get "/signup"   => "devise/registrations#new"
    get 'login', to: 'devise/sessions#new'
    get 'agency_details', to: 'devise/registrations#edit'
    put 'update_agency', to: 'users/registrations#update', as: "update_agency"

  end

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  root 'dashboard#index'

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base

  validates_presence_of :number

end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]

  # GET /phone_numbers
  # GET /phone_numbers.json
  def index
    @phone_numbers = PhoneNumber.all
  end

  # GET /phone_numbers/1
  # GET /phone_numbers/1.json
  def show
  end

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to phone_numbers_url, notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:number, :is_used)
    end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/_form.html.erb
<%= form_for(@phone_number) do |f| %>
  <div class="m-t" role="form" >
    <% if @phone_number.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@phone_number.errors.count, "error") %> prohibited this phone number from being saved:</h2>

        <ul>
        <% @phone_number.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>Create Phone Number </h5>
          <div class="ibox-tools">
              <a class="collapse-link">
                  <i class="fa fa-chevron-up"></i>
              </a>
              <a class="close-link">
                  <i class="fa fa-times"></i>
              </a>
          </div>
      </div>
      <div class="ibox-content">

          <div class="form-group">
            <label class="col-sm-2 control-label">Phone Number</label>
              <div class="row">
                <div class="col-sm-4">
                    <%= f.text_field :number, class:"form-control", :data => {:mask=> '+19999999999'} %>
                    <span class="help-block">+11234567890 </span>
                    <br>
                    <br>
                </div>
              </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Being Used</label>
              <div class="row">
                <div class="col-sm-4">
                    <%= f.check_box :is_used, class:"form-control", unchecked:"unchecked", onclick:"return false;" %>
                    <span class="help-block">Default is false. Cannot Change</span>
                    <br>
                    <br>
                </div>
              </div>
          </div>



          <div class="actions">
              <%= f.submit nil, class: "btn btn-primary block full-width m-b" %>
          </div>

          <div class="actions">
            <%if @phone_number.id%>
                <%= link_to "Delete Phone Number", phone_number_path(@phone_number), :method => :delete,  data: {confirm: 'Are you sure?' },
                  :class => "btn btn-danger block half-width m-b btn-outline" %>
            <%end%>
          </div>
      </div>
    </div>

  </div>

<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Editing Phone Number</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-10">
        <h2>Phone Numbers</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'dashboard', :action => 'index' %>">Dashboard</a>
            </li>
            <li class="active">
                <strong>Phone Numbers</strong>
            </li>
        </ol>
        <a href="/phone_numbers/new" class="btn btn-w-m btn-success">Create Phone Number</a>

    </div>
    <div class="col-sm-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
<div class="col-sm-12">
<div class="ibox float-e-margins">
<div class="ibox-title">
    <h5>Numbers</h5>


    <div class="ibox-tools">
        <a class="collapse-link">
        </a>
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        </a>
        <a class="close-link">
        </a>
    </div>
</div>
<div class="ibox-content">

<table class="table table-striped table-bordered table-hover dataTables-example">
<thead>
<tr>
    <th>Date</th>
    <th>Phone Number</th>
    <th>User</th>
    <th>Being Used</th>
    <th>Last Updated</th>
</tr>
</thead>
<tbody>
  <% @phone_numbers.each do |c| %>
    <tr class="gradeX">
        <td class="center"><div style="font-size:0; color:transparent;"><%= c.created_at%></div> <%=local_time(c.created_at)%></td>
        <%if c.number%>
          <td><%= link_to c.number, edit_phone_number_path(c) %></td>
        <%else%>
          <td></td>
        <%end%>
        <%if c.user_id %>
          <td><%= "#{User.find_by_id(c.user_id).name} / #{User.find_by_id(c.user_id).agency_name}" %></td>
        <%else%>
          <td>No User</td>
        <%end%>
        <td><%=c.is_used%></td>
        <td class="center"><div style="font-size:0; color:transparent;"><%= c.updated_at%></div> <%=local_time(c.updated_at)%></td>
    </tr>
  <% end %>
</tbody>
<tfoot>
  <tr>
    <th>Date</th>
    <th>Phone Number</th>
    <th>User</th>
    <th>Being Used</th>
    <th>Last Updated</th>
  </tr>
</tfoot>
</table>

</div>
</div>
</div>
</div>

</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.dataTables-example').DataTable({
        pageLength: 25,
        responsive: true,
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            { extend: 'copy'},
            {extend: 'csv'},
            {extend: 'excel', title: 'Phone Numbers | Callia'},
            {extend: 'pdf', title: 'Phone Numbers | Callia'}

        ]

    });

    var $image = $(".image-crop > img")
    $($image).cropper({
        aspectRatio: 1.618,
        preview: ".img-preview",
        done: function (data) {
            // Output the result data for cropping image.
        }
    });
    var $inputImage = $("#inputImage");
    if (window.FileReader) {
        $inputImage.change(function () {
            var fileReader = new FileReader(),
                    files = this.files,
                    file;
            if (!files.length) {
                return;
            }
            file = files[0];
            if (/^image\/\w+$/.test(file.type)) {
                fileReader.readAsDataURL(file);
                fileReader.onload = function () {
                    $inputImage.val("");
                    $image.cropper("reset", true).cropper("replace", this.result);
                };
            } else {
                showMessage("Please choose an image file.");
            }
        });
    } else {
        $inputImage.addClass("hide");
    }
    $("#download").click(function () {
        window.open($image.cropper("getDataURL"));
    });
    $("#zoomIn").click(function () {
        $image.cropper("zoom", 0.1);
    });
    $("#zoomOut").click(function () {
        $image.cropper("zoom", -0.1);
    });
    $("#rotateLeft").click(function () {
        $image.cropper("rotate", 45);
    });
    $("#rotateRight").click(function () {
        $image.cropper("rotate", -45);
    });
    $("#setDrag").click(function () {
        $image.cropper("setDragMode", "crop");
    });
    $('#data_1 .input-group.date').datepicker({
        todayBtn: "linked",
        keyboardNavigation: false,
        forceParse: false,
        calendarWeeks: true,
        autoclose: true
    });
    $('#data_2 .input-group.date').datepicker({
        todayBtn: "linked",
        keyboardNavigation: false,
        forceParse: false,
        calendarWeeks: true,
        autoclose: true
    });
    $('#data_3 .input-group.date').datepicker({
        startView: 2,
        todayBtn: "linked",
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true
    });
    $('#data_4 .input-group.date').datepicker({
        minViewMode: 1,
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true,
        todayHighlight: true
    });
    $('#data_5 .input-daterange').datepicker({
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true
    });
    var elem = document.querySelector('.js-switch');
    var switchery = new Switchery(elem, { color: '#1AB394' });
    var elem_2 = document.querySelector('.js-switch_2');
    var switchery_2 = new Switchery(elem_2, { color: '#ED5565' });
    var elem_3 = document.querySelector('.js-switch_3');
    var switchery_3 = new Switchery(elem_3, { color: '#1AB394' });
    var elem_4 = document.querySelector('.js-switch_4');
    var switchery_4 = new Switchery(elem_4, { color: '#f8ac59' });
    switchery_4.disable();
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green',
    });
    $('.demo1').colorpicker();
    var divStyle = $('.back-change')[0].style;
    $('#demo_apidemo').colorpicker({
        color: divStyle.backgroundColor
    }).on('changeColor', function (ev) {
                divStyle.backgroundColor = ev.color.toHex();
            });
    $('.chosen-select').chosen({width: "100%"});
    $(".select2_demo_1").select2();
    $(".select2_demo_2").select2();
    $(".select2_demo_3").select2({
        placeholder: "Select a state",
        allowClear: true
    });
    $(".touchspin1").TouchSpin({
        buttondown_class: 'btn btn-white',
        buttonup_class: 'btn btn-white'
    });
    $(".touchspin2").TouchSpin({
        min: 0,
        max: 100,
        step: 0.1,
        decimals: 2,
        boostat: 5,
        maxboostedstep: 10,
        postfix: '%',
        buttondown_class: 'btn btn-white',
        buttonup_class: 'btn btn-white'
    });
    $(".touchspin3").TouchSpin({
        verticalbuttons: true,
        buttondown_class: 'btn btn-white',
        buttonup_class: 'btn btn-white'
    });
    $("#ionrange_1").ionRangeSlider({
        min: 0,
        max: 5000,
        type: 'double',
        prefix: "$",
        maxPostfix: "+",
        prettify: false,
        hasGrid: true
    });
    $("#ionrange_2").ionRangeSlider({
        min: 0,
        max: 10,
        type: 'single',
        step: 0.1,
        postfix: " carats",
        prettify: false,
        hasGrid: true
    });
    $("#ionrange_3").ionRangeSlider({
        min: -50,
        max: 50,
        from: 0,
        postfix: "°",
        prettify: false,
        hasGrid: true
    });
    $("#ionrange_4").ionRangeSlider({
        values: [
            "January", "February", "March",
            "April", "May", "June",
            "July", "August", "September",
            "October", "November", "December"
        ],
        type: 'single',
        hasGrid: true
    });
    $("#ionrange_5").ionRangeSlider({
        min: 10000,
        max: 100000,
        step: 100,
        postfix: " km",
        from: 55000,
        hideMinMax: true,
        hideFromTo: false
    });
    $(".dial").knob();
    $("#basic_slider").noUiSlider({
        start: 40,
        behaviour: 'tap',
        connect: 'upper',
        range: {
            'min': 20,
            'max': 80
        }
    });
    $("#range_slider").noUiSlider({
        start: [40, 60],
        behaviour: 'drag',
        connect: true,
        range: {
            'min': 20,
            'max': 80
        }
    });
    $("#drag-fixed").noUiSlider({
        start: [40, 60],
        behaviour: 'drag-fixed',
        connect: true,
        range: {
            'min': 20,
            'max': 80
        }
    });
    $('.clockpicker').clockpicker();
    $('input[name="daterange"]').daterangepicker();
    $('#reportrange span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));
    $('#reportrange').daterangepicker({
        format: 'MM/DD/YYYY',
        startDate: moment().subtract(29, 'days'),
        endDate: moment(),
        minDate: '01/01/2012',
        maxDate: '12/31/2015',
        dateLimit: { days: 60 },
        showDropdowns: true,
        showWeekNumbers: true,
        timePicker: false,
        timePickerIncrement: 1,
        timePicker12Hour: true,
        ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Last 7 Days': [moment().subtract(6, 'days'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        opens: 'right',
        drops: 'down',
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-primary',
        cancelClass: 'btn-default',
        separator: ' to ',
        locale: {
            applyLabel: 'Submit',
            cancelLabel: 'Cancel',
            fromLabel: 'From',
            toLabel: 'To',
            customRangeLabel: 'Custom',
            daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr','Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            firstDay: 1
        }
    }, function(start, end, label) {
        console.log(start.toISOString(), end.toISOString(), label);
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    });
    $('.dual_select').bootstrapDualListbox({
        selectorMinimalHeight: 160
    });
    $('.tagsinput').tagsinput({
        tagClass: 'label label-primary'
    });


});



</script>

<% end %>

app/views/phone_numbers/new.html.erb
<h1>New Phone Number</h1>

<%= render 'form' %>

<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @phone_number.number %>
</p>

<p>
  <strong>Is used:</strong>
  <%= @phone_number.is_used %>
</p>

<%= link_to 'Edit', edit_phone_number_path(@phone_number) %> |
<%= link_to 'Back', phone_numbers_path %>