config/routes.rb
Rails.application.routes.draw do

  resources :sections
  devise_for :admins
  resources :phone_numbers
  mount Koudoku::Engine, at: 'koudoku'
  scope module: 'koudoku' do
    get 'pricing' => 'subscriptions#index', as: 'pricing'
  end

  resources :tutorials
  resources :services
  resources :activities
  resources :settings
  resources :reminders
  resources :recurring_shifts
  resources :shifts
  resources :clients
  resources :contacts
  resources :offices do
    collection do
      get :show_telephone
    end
  end

  resources :caregivers
  resources :calls
  resources :dashboard
  resources :reports
  resources :landing
  resources :schedule
  resources :digital_signature

  get "caregivers/show"
  post 'calls/voice' => 'calls#voice'
  match 'calls/get_employee' => 'calls#get_employee', via: [:get, :post], as: 'get_employee'
  match 'calls/verify_caller' => 'calls#verify_caller', via: [:get, :post], as: 'verify_caller'
  match 'calls/play_voice' => 'calls#play_voice', via: [:get, :post], as: 'play_voice'
  match 'calls/clock_out' => 'calls#clock_out', via: [:get, :post], as: 'clock_out'
  match 'calls/clock_in' => 'calls#clock_in', via: [:get, :post], as: 'clock_in'
  match 'calls/ask' => 'calls#ask', via: [:get, :post], as: 'ask'
  match 'calls/answer' => 'calls#answer', via: [:get, :post], as: 'answer'
  match 'calls/ask_for_employee_code' => 'calls#ask_for_employee_code', via: [:get, :post], as: 'ask_for_employee_code'
  get 'display_client' => "clients#display_client"
  get 'call_logs' => "reports#call_logs", as: 'call_logs'
  post 'call_logs' => "reports#call_logs", as: 'search_call_logs'
  get 'timecard_report' => "reports#timecard_report", as: 'timecard_report'
  post 'timecard_report' => "reports#timecard_report", as: 'search_timecard_report'
  get 'activity_report' => "reports#activity_report", as: 'activity_report'
  post 'activity_report' => "reports#activity_report", as: 'search_activity_report'
  get 'custom_prompt_report' => "reports#custom_prompt_report", as: 'custom_prompt_report'
  post 'custom_prompt_report' => "reports#custom_prompt_report", as: 'search_custom_prompt_report'
  get 'evv_recording' => "reports#evv_recording", as: 'evv_recording'
  post 'evv_recording' => "reports#evv_recording", as: 'search_evv_recording'
  get 'quickstart' => "tutorials#quickstart", as: 'quickstart'
  get 'quickstart_step2' => "tutorials#quickstart_step2", as: 'quickstart_step2'
  get 'quickstart_step3' => "tutorials#quickstart_step3", as: 'quickstart_step3'
  get 'terms_and_conditions' => "tutorials#terms_and_conditions", as: 'terms_and_conditions'
  match 'digital_signature/confirm' => 'digital_signature#confirm', via: [:get, :post], as: 'confirm'
  match 'digital_signature/select_client' => 'digital_signature#select_client', via: [:get, :post], as: 'select_client'
  match 'display_question' => 'digital_signature#display_question', via: [:get, :post], as: 'display_question'
  get 'employee_code' => "digital_signature#employee_code", as: 'employee_code'
  get 'verify' => "digital_signature#verify", as: 'verify'
  get 'timesheet' => "digital_signature#timesheet", as: 'timesheet'
  get 'verify_location' => "digital_signature#verify_location", as: 'verify_location'
  put 'update_timesheet', to: 'digital_signature#update_timesheet', as: "update_timesheet"
  get 'congrats' => "digital_signature#congrats", as: 'congrats'

  get 'obtain_prospect' => "settings#obtain_prospect", as: 'obtain_prospect'
  get 'export', to: 'settings#export', as: :foo_export
  get 'call_process' => "dashboard#call_process", as: 'call_process'
  get 'digital_timesheet_process' => "dashboard#digital_timesheet_process", as: 'digital_timesheet_process'
  get 'weekly_report' => "reports#weekly_report", as: 'weekly_report'
  post 'weekly_report' => "reports#weekly_report", as: 'post_weekly_report'
  get 'search_weekly_report' => "reports#search_weekly_report", as: 'search_weekly_report'

  match 'tutorials/demo_explained' => 'tutorials#demo_explained', via: [:get, :post], as: 'demo_explained'
  post 'demo' => "tutorials#demo", as: 'post_demo'
  get 'demo' => "tutorials#demo", as: 'demo'
  
  get 'start_guide' => "tutorials#start_guide", as: 'start_guide'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get "/signup"   => "devise/registrations#new"
    get 'login', to: 'devise/sessions#new'
    get 'agency_details', to: 'devise/registrations#edit'
    put 'update_agency', to: 'users/registrations#update', as: "update_agency"

  end

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  root 'dashboard#index'

end

app/models/call.rb
class Call < ActiveRecord::Base

  belongs_to :user
  belongs_to :client
  belongs_to :caregiver
  belongs_to :shift
  has_one :activity
  has_many :services
  has_one :clock_out_call, :class_name => 'Call', :foreign_key => :clock_out_call_id
  has_one :clock_in_call, :class_name => 'Call', :foreign_key => :clock_in_call_id


# caregiver has made call from client's phone, check for shift
  def save_activity(text, call, client, caregiver)
    activity = Activity.new(activity:text)
    activity.client = client
    activity.caregiver = caregiver

    #check for shift
    if call.shift
      activity.shift = call.shift
    end

    activity.save
    count_calls
  end

  def count_calls
    # set the call to the user incharge so that we know who to pay
    if self.client
      # link from client
      user = self.client.office.user
      if user
        # add call to user
        user.calls = self
      end
    elsif self.caregiver
      # link from client
      user = self.caregiver.office.user
      if user
        # add call to user
        user.calls = self
      end
    end
  end

end

app/controllers/digital_signature_controller.rb
require 'twilio-ruby'

class DigitalSignatureController < ApplicationController



  def employee_code #1

  end

  def confirm #2
    something = params[:anything]
    if something
      @code = something[:code]
      @caregivers = Caregiver.all.where(:employee_code => "#{@code}")
    end
  end

  def verify #3
    # send a text to this number to verify number
    id = params[:id]
    @id = params[:id]
    caregiver = Caregiver.all.where(id: id).first
    @code = send_text(caregiver)

    # caregiver should enter the number to verify

  end

  def select_client
    # make sure to send the caregiver info for the user
    id = params[:id]
    @id = params[:id]
    verify = params[:verify]
    code = params[:anything][:code]
    caregiver = Caregiver.all.where(id: id).first

    @company_name = caregiver.office.user.agency_name
    unless code == verify
      #redirect to invalid page
      redirect_to "/verify?id=#{id}"
    end
    caregiver = Caregiver.all.where(id: id).first
    @clients = caregiver.user.clients

  end

  def timesheet #4
    id = params[:c_id]
    @id = params[:c_id]
    # verify = params[:verify]
    # code = params[:anything][:code]
    caregiver = Caregiver.all.where(id: id).first
    @caregiver = caregiver

    client = Client.find_by_id(params[:client_id])
    @client = client
    # @company_name = caregiver.office.user.agency_name
    # unless code == verify
    #   #redirect to invalid page
    #   redirect_to "/verify?id=#{id}"
    # end
    #display the timesheet form and verify location

    # if params[:client_id]
    #   get_client_location
    # end

    # @timesheet = Call.new
    # @timesheet.log_type = "Timesheet: Incomplete"
    # @timesheet.user = caregiver.user
    # @timesheet.caregiver = caregiver
    # @timesheet.client = client
    # @timesheet.save
    # set_services
    # @services = @timesheet.services


  end

  def send_text(c)
    #send caregiver a text to verify themselves
    if c.phone_number and c.user
      #send text
      p "sending text"

      client = Twilio::REST::Client.new(
        ENV['TWILIO_ACCOUNT_SID'], #set these two
        ENV['TWILIO_AUTH_TOKEN']
      )
      code = 5.times.map { rand(1..9) }.join.to_i

      client.messages.create(
        from: "#{c.user.call_number}",
        to: "#{c.phone_number}",
        body: "Verification code: #{code}"
      )
      return code
    else
      p "not sending text"
      p "#{c.phone_number} | #{c.user}"
    end
  end

  def get_client_location
    client = Client.find_by_id(params[:client_id])
    @client = client

    res = Geokit::Geocoders::GoogleGeocoder.reverse_geocode "#{client.address} #{client.city},  #{client.state}"

    @client_lat = res.latitude
    @client_long = res.longitude
  end

  def verify_location
    id = params[:id]
    @id = id
    caregiver = Caregiver.all.where(id: id).first
    @count = 0

    if params[:client_id]
      get_client_location
    end


  end

  def verified_location
    p @count
    if @count == 1
      redirect_to :action => "timesheet", client_id: @client.id, id: @id
    end
    @count = 1
    p @count

  end
  helper_method :verified_location

  def update_timesheet
    # create call, save services to the call, save caregiver and client to the call
    @timesheet = Call.new(call_params)

    @timesheet.log_type = "Digital Timesheet: Completed"
    if @timesheet.save
      redirect_to "/congrats"
    end
  end

  def set_services
    # use in the timesheet func
    @service_ids = []
    @caregiver.user.services.each do |s|
      service = Service.new
      service.service = s.service
      service.save
      @timesheet.services.push service# don't set the service.user, that is for the user to tweak only
      @service_ids.push s.id
    end

    @services = @timesheet.services
    @t_id = @timesheet.id
    if @service_ids[0] #should be 0
      @question = Service.find_by_id(@service_ids[0]).service
    end

  end


  def display_question

    order = params[:order].to_i
    @order = order

    id = params[:c_id].to_i
    @id = params[:c_id].to_i #caregiver id

    caregiver = Caregiver.all.where(id: id).first
    @caregiver = caregiver

    client = Client.find_by_id(params[:client_id])
    @client = client

    @t_id = params[:t_id].to_i #timesheet id
    if @t_id
      @timesheet = Call.find_by_id(@t_id)
    end
    t_id = @t_id
    @service_ids = []#params[:service_ids]
    if params[:service_ids]
      params[:service_ids].tr('[]', '').split(',').map(&:to_i).each do |n|
        @service_ids.push n.to_i
      end
    end

    response = params[:response]

    if response
      # Set answer, go to next question
      service = Service.find_by_id(@service_ids[order])
      p @service_ids
      p params[:service_ids]
      p @service_ids[order]
      p service

      if service
        service.response = response
        unless @timesheet.services.include? service
          @timesheet.services.push service
        end
        service.save
      end

      @next_url = "/display_question?client_id=#{client.id}&c_id=#{@id}&order=#{order + 1}&t_id=#{@t_id}&service_ids=#{@service_ids}"
      redirect_to @next_url
    else
      # display_question
      @timesheet = Call.find_by_id(@t_id)

      if order > 0 and @t_id and @timesheet
        t_id = @t_id

        if @service_ids[order] #test, DOESNT WORK
          @question = Service.find_by_id(@service_ids[order]).service

          @next_url = "/display_question?client_id=#{client.id}&c_id=#{@id}&order=#{order + 1}&t_id=#{@t_id}&service_ids=#{@service_ids}"
        else
          # done, redirect to timesheet
          redirect_to "/timesheet?client_id=#{@timesheet.client.id}&c_id=#{@timesheet.caregiver.id}"
        end
      else
        # order == 0
        # create timesheet here then continue to display the first question
        # send t_id through, send order through

        @timesheet = Call.new
        @timesheet.log_type = "Timesheet: Incomplete"
        @timesheet.save
        @timesheet.user = caregiver.user
        @timesheet.save
        @timesheet.caregiver = caregiver
        @timesheet.client = client
        @timesheet.save

        set_services

      end
    end
  end

  def service_params
    params.require(:service).permit(:service, :response)
  end

  def call_params
    params.require(:call).permit(:caller_number, :called_number, :service_ids, :order)
  end

end

app/helpers/digital_signature_helper.rb
module DigitalSignatureHelper
end

app/views/digital_signature/confirm.html.erb
<p id="notice"><%= notice %></p>

<div class="row wrapper border-bottom white-bg page-heading">

<div class="col-sm-2">

</div>
        </div>
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
<div class="col-sm-12">
<div class="ibox float-e-margins">
<div class="ibox-title">
    <h5>Is this You?</h5>
    <div class="ibox-tools">
        <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
        </a>
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-wrench"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li>
                <a href="#">Config option 1</a>
            </li>
            <li>
                <a href="#">Config option 2</a>
            </li>
        </ul>
        <a class="close-link">
            <i class="fa fa-times"></i>
        </a>
    </div>
</div>
<div class="ibox-content">

<table class="table table-striped table-bordered table-hover dataTables-example">
<thead>
<tr>
    <th>Name</th>
    <th>Employee Code</th>
    <th>Office</th>
    <th>City / State</th>
    <th>Confirm</th>
</tr>
</thead>
<tbody>
  <% @caregivers.each do |c| %>
    <tr class="gradeX">
        <td><%= link_to c.name, verify_path(id: c.id) %></td>
        <td class="center"><%=c.employee_code%></td>
        <%if c.office and c.office.name%>
          <td><%=c.office.name%></td>
        <%else%>
          <td>No Office</td>
        <%end%>
        <td class="center"><%=c.city%> / <%=c.state%></td>
        <td><%= link_to "Select", verify_path(id: c.id) %></td>
    </tr>
  <% end %>
</tbody>
<tfoot>
  <tr>
      <th>Name</th>
      <th>Employee Code</th>
      <th>Office</th>
      <th>City / State</th>
      <th>Confirm</th>
  </tr>
</tfoot>
</table>

</div>
</div>
</div>
</div>

</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.dataTables-example').DataTable({
        pageLength: 25,
        responsive: true,
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            { extend: 'copy'},
            {extend: 'csv'},
            {extend: 'excel', title: 'ExampleFile'},
            {extend: 'pdf', title: 'ExampleFile'},

            {extend: 'print',
                customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');

                    $(win.document.body).find('table')
                            .addClass('compact')
                            .css('font-size', 'inherit');
                }
            }
        ]

    });


});



</script>

<% end %>

app/views/digital_signature/congrats.html.erb
Congrats you have successfully Logged your work for the day!!

app/views/digital_signature/display_question.html.erb
<%= form_for :anything, url: "display_question?client_id=#{@client.id}&c_id=#{@id}&order=#{@order}&t_id=#{@t_id}&service_ids=#{@service_ids}" do |f| %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

  <div class="m-t" role="form" >

    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>Timesheet Question </h5>
          <div class="ibox-tools">
              <a class="collapse-link">
                  <i class="fa fa-chevron-up"></i>
              </a>
              <a class="close-link">
                  <i class="fa fa-times"></i>
              </a>
          </div>
      </div>
      <div class="ibox-content">

          <div class="form-group">
            <label class="col-sm-2 control-label"><%=@question%></label>
              <div class="row">
                <div class="col-sm-4">
                    <div class="actions">
                      <%= f.submit "Yes", name: "response", value: "Yes", class: "btn btn-success block full-width m-b" %>
                      <%= f.submit "No", name: "response", value: "No", class: "btn btn-danger block full-width m-b" %>
                    </div>
                    <br>
                    <br>
                </div>
              </div>
          </div>





      </div>
    </div>

  </div>

<% end %>

app/views/digital_signature/employee_code.html.erb
<%= form_for :anything, url: "digital_signature/confirm" do |f| %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

  <div class="m-t" role="form" >

    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>Create Phone Number </h5>
          <div class="ibox-tools">
              <a class="collapse-link">
                  <i class="fa fa-chevron-up"></i>
              </a>
              <a class="close-link">
                  <i class="fa fa-times"></i>
              </a>
          </div>
      </div>
      <div class="ibox-content">

          <div class="form-group">
            <label class="col-sm-2 control-label">Please Enter Code</label>
              <div class="row">
                <div class="col-sm-4">
                    <%= f.text_field :code, class:"form-control" %>
                    <span class="help-block"> </span>
                    <br>
                    <br>
                </div>
              </div>
          </div>




          <div class="actions">
              <%= f.submit "Continue", class: "btn btn-primary block full-width m-b" %>
          </div>

      </div>
    </div>

  </div>

<% end %>

app/views/digital_signature/select_client.html.erb
<p id="notice"><%= notice %></p>

<div class="row wrapper border-bottom white-bg page-heading">

<div class="col-sm-2">

</div>
        </div>
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
<div class="col-sm-12">
<div class="ibox float-e-margins">
<div class="ibox-title">
    <h5>Choose your Patient</h5>
    <div class="ibox-tools">
        <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
        </a>
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-wrench"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li>
                <a href="#">Config option 1</a>
            </li>
            <li>
                <a href="#">Config option 2</a>
            </li>
        </ul>
        <a class="close-link">
            <i class="fa fa-times"></i>
        </a>
    </div>
</div>
<div class="ibox-content">

<table class="table table-striped table-bordered table-hover dataTables-example">
<thead>
<tr>
    <th>Name</th>
    <th>Address</th>
    <th>Office</th>
    <th>Confirm</th>
</tr>
</thead>
<tbody>
  <% @clients.each do |c| %>
    <tr class="gradeX">
        <td><%= link_to c.name, verify_location_path(client_id: c.id, id: @id) %></td>
        <td class="center"><%=c.address%></td>
        <%if c.office and c.office.name%>
          <td><%=c.office.name%></td>
        <%else%>
          <td>No Office</td>
        <%end%>
        <td><%= link_to "Select", verify_location_path(client_id: c.id, id: @id) %></td>
    </tr>
  <% end %>
</tbody>
<tfoot>
  <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Office</th>
      <th>Confirm</th>
  </tr>
</tfoot>
</table>

</div>
</div>
</div>
</div>

</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.dataTables-example').DataTable({
        pageLength: 25,
        responsive: true,
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
          
        ]

    });


});



</script>

<% end %>

app/views/digital_signature/timesheet.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-10">
        <h2><%=@company_name%> Timesheet</h2>
</div>
<div class="col-sm-2">

</div>
        </div>
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-sm-12">
        <div class="ibox">
            <div class="ibox-title">
                <h5><%= @company_name%></h5>
            </div>
            <div class="ibox-content">
                <h2>
                    Digital Timesheet Form
                </h2>

                <form id="form" action="<%=update_timesheet_path%>" class="wizard-big" method="post">
                    <h1>Account</h1>
                    <fieldset>
                        <h2>Account Information</h2>
                        <div class="row">
                            <div class="col-sm-8">
                                <div class="form-group">
                                    <label>Username *</label>
                                    <input id="userName" name="userName" type="text" class="form-control required">
                                </div>

                                <div class="form-group">
                                  <label>Start Time *</label>
                                  <div class="input-group clockpicker" data-autoclose="true">
                                    <input type="time" class="form-control" value="09:30" >
                                    <span class="input-group-addon">
                                        <span class="fa fa-clock-o"></span>
                                    </span>
                                  </div>
                                </div>

                            </div>
                            <div class="col-sm-4">
                                <div class="text-center">
                                    <div style="margin-top: 20px">
                                        <i class="fa fa-sign-in" style="font-size: 180px;color: #e5e5e5 "></i>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </fieldset>
                    <h1>Profile</h1>
                    <fieldset>
                        <h2>Profile Information</h2>
                        <div class="row">

                        </div>
                    </fieldset>

                    <h1>Warning</h1>
                    <fieldset>
                        <div class="text-center" style="margin-top: 120px">
                            <h2>You did it Man :-)</h2>
                        </div>
                    </fieldset>

                    <h1>Finish</h1>
                    <fieldset>
                        <h2>Terms and Conditions</h2>
                        <input id="acceptTerms" name="acceptTerms" type="checkbox" class="required"> <label for="acceptTerms">I agree with the Terms and Conditions.</label>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>

</div>
</div>


<% content_for :javascript do %>

<script type="text/javascript">
$(function() {
    $("#wizard").steps();
    $("#form").steps({
        bodyTag: "fieldset",
        onStepChanging: function (event, currentIndex, newIndex) {
            // Always allow going backward even if the current step contains invalid fields!
            if (currentIndex > newIndex) {
                return true;
            }
            // Forbid suppressing "Warning" step if the user is to young
            if (newIndex === 3 && Number($("#age").val()) < 18) {
                return false;
            }
            var form = $(this);
            // Clean up if user went backward before
            if (currentIndex < newIndex) {
                // To remove error styles
                $(".body:eq(" + newIndex + ") label.error", form).remove();
                $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
            }
            // Disable validation on fields that are disabled or hidden.
            form.validate().settings.ignore = ":disabled,:hidden";
            // Start validation; Prevent going forward if false
            return form.valid();
        },
        onStepChanged: function (event, currentIndex, priorIndex) {
            // Suppress (skip) "Warning" step if the user is old enough.
            if (currentIndex === 2 && Number($("#age").val()) >= 18) {
                $(this).steps("next");
            }
            // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
            if (currentIndex === 2 && priorIndex === 3) {
                $(this).steps("previous");
            }
        },
        onFinishing: function (event, currentIndex) {
            var form = $(this);
            // Disable validation on fields that are disabled.
            // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
            form.validate().settings.ignore = ":disabled";
            // Start validation; Prevent form submission if false
            return form.valid();
        },
        onFinished: function (event, currentIndex) {
            var form = $(this);
            // Submit form input
            form.submit();
        }
    }).validate({
                errorPlacement: function (error, element) {
                    element.before(error);
                },
                rules: {
                    confirm: {
                        equalTo: "#password"
                    }
                }
            });
});

$('.clockpicker').clockpicker();

$(document).load(function(){
  verify_location();
});

</script>

<% end %>

app/views/digital_signature/verify.html.erb
<%= form_for :anything, url: "digital_signature/select_client" do |f| %>
  <div class="m-t" role="form" >

    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>We've sent you a text. </h5>
          <div class="ibox-tools">
              <a class="collapse-link">
                  <i class="fa fa-chevron-up"></i>
              </a>
              <a class="close-link">
                  <i class="fa fa-times"></i>
              </a>
          </div>
      </div>
      <div class="ibox-content">

          <div class="form-group">
            <label class="col-sm-2 control-label">Please Enter Verification Code</label>
              <div class="row">
                <div class="col-sm-4">
                    <%= f.text_field :code, class:"form-control" %>
                    <span class="help-block"> </span>
                    <br>
                    <br>
                </div>
              </div>
          </div>

          <div class="row">
            <input type="hidden" name="verify" value="<%=@code%>">
            <input type="hidden" name="id" value="<%=@id%>">
                <br>
          </div>


          <div class="actions">
              <%= f.submit "Verify", class: "btn btn-primary block full-width m-b" %>
          </div>

      </div>
    </div>

  </div>

<% end %>

app/views/digital_signature/verify_location.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

  <div class="m-t" role="form" >

    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>Verify your Location </h5>
          <div class="ibox-tools">
              <a class="collapse-link">
                  <i class="fa fa-chevron-up"></i>
              </a>
              <a class="close-link">
                  <i class="fa fa-times"></i>
              </a>
          </div>
      </div>
      <div class="ibox-content">


        <button id="verify_location" name="verify_location" onclick="getLocation();" data-style="slide-right" class="ladda-button btn btn-primary block full-width m-b">Verify Location</button>
        <p id="demo"></p>

      </div>
    </div>

  </div>



  <% content_for :javascript do %>

  <script type="text/javascript">

  $(document).load(function(){
    verify_location();
  });

  function getLocation(){
      if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(showPosition);
      } else {
          var x = document.getElementById("demo");
          x.innerHTML = "Geolocation is not supported by this browser.";
      }
  }

  function showPosition(position) {
      var x = document.getElementById("demo");
      x.innerHTML = "Latitude: " + position.coords.latitude + "<br>Longitude: " + position.coords.longitude;
      var client_lat = <%= @client_lat %>;
      var client_long = <%= @client_long %>;
      var current_lat = position.coords.latitude ;
      var current_long = position.coords.longitude;

      if (((current_lat >= (client_lat - 0.0019)) && (current_lat <= client_lat)) || ((current_lat <= (client_lat + 0.0019)) && (current_lat >= client_lat)) || (current_lat == (client_lat - 0.0019))){
        if (((current_long >= (client_long - 0.0019)) && (current_long <= client_long)) || ((current_long <= (client_long + 0.0019)) && (current_long >= client_long)) || (current_long == (client_long - 0.0019))){
          // This means that the user is there
          x.innerHTML = "Verified";
          window.location = "/display_question?client_id=<%=@client.id%>&c_id=<%=@id%>&order=0" //"/timesheet?client_id=<%=@client.id%>&c_id=<%=@id%>"
        }else{
          x.innerHTML = "UnVerified Longitude" + "<br>" + "You don't seem to be located at <%=@client.address%>";// +
          // "<br>" + current_lat + current_long + "<br>" + client_lat + client_long;
        }
      }else{
        x.innerHTML = "UnVerified Latitude" + "<br>" + "You don't seem to be located at <%=@client.address%>";// +
        // "<br>" + current_lat + current_long + "<br>" + client_lat + client_long;
      }

  }
  </script>

  <% end %>